### ISSUE TITLE
Translate Kovri README in all available languages

### ISSUE THREAD

**Issue by erciccione** [monero-project/kovri-docs#63]
The README of the 'kovri' repository needs to be updated. It was already copied in every language subfolder in this repository and it only need to be translated. Follow the missing languages and the link to the related README uploaded on 'kovri-docs'. It will then linked from the main README from the multilingual section ([Link](https://github.com/monero-project/kovri#multilingual-readme))

- [x] **Italian** - updated by #53 
- [x] **French** - updated by #58 
- [x] **Spanish** - updated by #64 
- [ ] **Russian** - [README](https://github.com/monero-project/kovri-docs/blob/master/i18n/ru/README.md) - *[Task on Taiga](https://taiga.getmonero.org/project/erciccione-monero-localization/task/312)*
- [x] **German** - updated by #73 
- [ ] **Danish** - [README](https://github.com/monero-project/kovri-docs/blob/master/i18n/da/README.md) - *[Task on Taiga](https://taiga.getmonero.org/project/erciccione-monero-localization/task/311)*

**Comment by erciccione** [comment]
Can anybody of the russian community work on this @LvMsterfild?
@cryptobench what about Danish? could you help?

**Comment by anonimal** [comment]
Note: the Italian/French need some minor updates against the current English README.

**Comment by ordtrogen** [comment]
This issue, in the repo 'kovri-docs', calls for translation of the README in another repo, 'kovri', right? But supposedly we're not supposed to fork the 'kovri' repo but this one.

I'm looking in kovri-docs\i18n\en  but I don't see a README there

Am I missing something?

**Comment by Josexv1** [comment]
@ordtrogen You have to translate the readme in your language.

**Comment by LvMsterfild** [comment]
@erciccione MoneroRus will continue...

**Comment by ordtrogen** [comment]
I won't deny you have a point @Josexv1 , but I wanted to add a new language (sv_SE).

I'd have thought that the 'en' folder here in 'kovri-docs' was there to provide the source for translation, why else is it there? And like I said, the 'en' folder doesn't have a README file.

**Comment by ordtrogen** [comment]
I won't deny you have a point, @Josexv1 , but I wanted to add a new language (sv_SE).

I'd have thought the 'en' folder here in 'kovri-docs' provided the source for any language, why else would it be here? and like I said, it has no README file even though it has a bunch of other files.

**Comment by anonimal** [comment]
@ordtrogen The README is within the kovri repo, not kovri-docs. *That* is the source for translation. We can't put the file in kovri-docs because then the kovri repo would have no README (we technically *can* put it in kovri-docs, but then how do we solve the redundancy issue?).

**Comment by ordtrogen** [comment]
Ah, so the files in kovri-docs\i18n\en belong to this repo whereas the README in question belongs to the kovri repo. Now it makes sense.

And the files in kovri-docs\i18n\[LANG] are sortof in between?

**Comment by anonimal** [comment]
>Ah, so the files in kovri-docs\i18n\en belong to this repo whereas the README in question belongs to the kovri repo. Now it makes sense.

Yes, sorry for the confusion. I wish we could have this simpler.

>And the files in kovri-docs\i18n[LANG] are sortof in between?

No, they'll exist entirely in the kovri-docs repo but kovri-site will pull from them so, any changes to kovri-docs will end up on the website.

**Comment by erciccione** [comment]
I opened #66 to add a template in 'kovri-docs' if that's ok for you @anonimal, this because the translated readme is slighlty different from the "original" one. i gave it the name `README_template` to avoid confusions

> @erciccione MoneroRus will continue...
@LvMsterfild Ok, thanks for that!

> Note: the Italian/French need some minor updates against the current English README.

@anonimal Ok, i will edit the italian one. @el00ruobuob can you take care of the french readme?

**Comment by el00ruobuob** [comment]
didn't i already?

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri-docs/issues/102 for details.
